xcassets:
    inputs: AdmiralButtonsViewer/AdmiralButtonsViewer/Resources/Assets.xcassets
    outputs:
        templatePath: Templates/Images.stencil
        output: AdmiralButtonsViewer/AdmiralButtonsViewer/Resources/Generated/Assets.swift
        params:
            publicAccess: 1
            allValues: 1
            enumName: Assets
