xcassets:
    inputs: Sources/Buttons/Resources/Images.xcassets
    outputs:
        templatePath: Templates/Images.stencil
        output: Sources/Buttons/Assets/Images.swift
        params:
            publicAccess: 1
            allValues: 1
            enumName: Assets
